### ISSUE TITLE
2 or 4 consecutive double-quotes ("""") are treated as strings and are now separated by a unintended space

### ISSUE THREAD

**Issue by pravynandas** [lenilsondc/vbspretty#1]
'======= Example 1 =============
buf.Add buf.Count, """"

Now became

buf.Add buf.Count, "" ""
'======= Example 2 =============
Case """" 

became

Case "" ""
'======= Example 3 =============
Set StringChunk = New RegExp
        StringChunk.Pattern = "([\s\S]*?)([""\\\x00-\x1f])"

became

Set StringChunk = New RegExp
    StringChunk.Pattern = "([\s\S]*?)([" "\\\x00-\x1f])"

**Comment by pravynandas** [comment]
### parsed.json value & type
![image](https://user-images.githubusercontent.com/4099637/124518757-4caa9980-ddb5-11eb-9986-fdd6a86fb209.png)

### Final output with unintended space
![image](https://user-images.githubusercontent.com/4099637/124518813-8085bf00-ddb5-11eb-8697-364203b58283.png)

**Comment by pravynandas** [comment]
Applied a fix to join any two consecutive STRING types into one STRING. Result is positive.

![image](https://user-images.githubusercontent.com/4099637/124542330-34587000-ddf1-11eb-90a8-778ddd9a7fee.png)

Will create a PR in a moment.

**Comment by lenilsondc** [comment]
I'll have a look into it.

**Comment by lenilsondc** [comment]
The problem is the double quotes `""` in vbscript means an escaped quote like `\"` in other languages; therefore, it shouldn't even be parsed in a separate string but on single string.

```vb
Dim test : test = "double quotes ("") is an escaped quote in vbscript"
```

**Comment by lenilsondc** [comment]
I'll provide a fix.

**Comment by lenilsondc** [comment]
Done, latest commit addresses this issue. Can you confirm it's working on your tests?

**Comment by pravynandas** [comment]
Fix working great. Thanks.

I closed the PR I created, since is no more needed. For now published new version on @vbsnext/vbs-pretty at npmjs. But as soon as your primary package available, I will start using it.

**Comment by lenilsondc** [comment]
@pravynandas There it goes https://www.npmjs.com/package/vbspretty

**Comment by pravynandas** [comment]
Awesome @lenilsondc . I used the package and is working great.  @vbsnext/vbs-pretty is now obsolete and is deleted.
